# Generated by Django 4.2.6 on 2024-05-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_transaction_notes_remove_transaction_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(default='No description', max_length=100),
            preserve_default=False,
        ),
    ]
